# Default values for package service.
nameOverride: package


replicaCount: 1


dockerregistrynamespace:
dockerregistry:


image:
  repository:
  tag:
  pullPolicy: IfNotPresent


# specify an installation/upgrade reason
reason: unknown


# probes
readinessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 40
  periodSeconds: 15
  timeoutSeconds: 2
  failureThreshold: 5

livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 50
  periodSeconds: 15


log:
  level: error


cosmosDb:
  collectionName:


# indicate what environment is meant to be installed/upgraded
envs:
  dev: false
  prod: false
  qa: false
  staging: false


current: false


# Horizontal Pod Autoscaling
autoscaling:
  enabled: false
  maxReplicas:
  minReplicas:
  targetCPUUtilizationPercentage:
service:
  targetPort: 80
  targetProtocol: TCP
