# Default values for dronescheduler.
replicaCount: 1


identity:
  clientid:
  resourceid:


dockerregistrynamespace:
dockerregistry:


image:
  repository:
  tag:
  pullPolicy: IfNotPresent


cosmosdb:
  id:
  collectionid:

keyvault:
  uri:


# probes
readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 40
  periodSeconds: 15
  timeoutSeconds: 2
  failureThreshold: 5
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 50
  periodSeconds: 15


# specify an installation/upgrade reason
reason: unknown


telemetry:
  level: "Error"


# indicate what environment is meant to be installed/upgraded
envs:
  dev: false
  prod: false
  qa: false
  staging: false


current: false


# Horizontal Pod Autoscaling
autoscaling:
  enabled: false
  maxReplicas:
  minReplicas:
  targetCPUUtilizationPercentage:
service:
  targetPort: 8080
  targetProtocol: TCP
